[package]
name = "pomelo-bootloader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", default-features = false }
uefi = { version = "0.13.0", features = ["alloc", "logger", "exts"] }
uefi-services = "0.10.0"

