cargo-features = ["per-package-target"]

[package]
name = "pomelo-kernel"
version = "0.1.0"
edition = "2021"
#forced-target = "x86_64-unknown-none-elf"

[dependencies]
anyhow = { version = "1.0", default-features = false }

